[
  "4 Dark Depths",
  "2 Dryad Arbor",
  "2 Forest",
  "1 Karakas",
  "4 Thespian's Stage",
  "1 Plains",
  "4 Wasteland",
  "4 Elvish Reclaimer",
  "3 Scavenging Ooze",
  "2 Sylvan Safekeeper",
  "2 Savannah",
  "4 Thalia, Guardian of Thraben",
  "1 Gaea's Cradle",
  "4 Path to Exile",
  "4 Noble Hierarch",
  "2 Sejiri Steppe",
  "2 Gaddock Teeg",
  "1 Scryb Ranger",
  "4 Tomik, Distinguished Advokist",
  "3 Knight of Autumn",
  "4 Knight of the Reliquary",
  "1 Ramunap Excavator",
  "4 Green Sun's Zenith",
  "4 Windswept Heath",
  "4 Wooded Foothills",
  "4 Crop Rotation",
  "4 Renegade Rallier",
  "4 Giver of Runes",
  "3 Surgical Extraction",
  "2 Reclamation Sage",
  "1 Titania, Protector of Argoth",
  "2 Force of Vigor",
  "4 Veil of Summer",
  "2 Collector Ouphe",
  "2 Tireless Tracker",
  "1 Garruk Relentless",
  "2 Council's Judgment",
  "1 Questing Beast",
  "4 Champion of the Parish",
  "2 Imperial Recruiter",
  "3 Kitesail Freebooter",
  "3 Meddling Mage",
  "2 Orzhov Pontiff",
  "2 Palace Jailer",
  "2 Phantasmal Image",
  "4 Reflector Mage",
  "1 Sanctum Prelate",
  "4 Thalia's Lieutenant",
  "4 Aether Vial",
  "4 Ancient Ziggurat",
  "4 Cavern of Souls",
  "3 Horizon Canopy",
  "4 Unclaimed Territory",
  "2 Containment Priest",
  "2 Deputy of Detention",
  "2 Faerie Macabre",
  "1 Kambal, Consul of Allocation",
  "2 Pia and Kiran Nalaar"
]