[
  "1 Hexdrinker",
  "1 Gaddock Teeg",
  "4 Windswept Heath",
  "4 Wasteland",
  "1 Misty Rainforest",
  "1 Wooded Foothills",
  "1 Verdant Catacombs",
  "3 Savannah",
  "2 Plains",
  "1 Karakas",
  "1 Horizon Canopy",
  "1 Gaea's Cradle",
  "2 Forest",
  "1 Dryad Arbor",
  "1 Blast Zone",
  "1 Knight of Autumn",
  "4 Knight of the Reliquary",
  "3 Mother of Runes",
  "4 Noble Hierarch",
  "2 Ranger - Captain of Eos",
  "1 Scavenging Ooze",
  "1 Scryb Ranger",
  "2 Stoneforge Mystic",
  "1 Sylvan Safekeeper",
  "4 Thalia, Guardian of Thraben",
  "1 Walking Ballista",
  "4 Green Sun's Zenith",
  "4 Swords to Plowshares",
  "1 Sword of Fire and Ice",
  "1 Sylvan Library",
  "1 Umezawa's Jitte",
  "Sideboard",
  "2 Chalice of the Void",
  "2 Choke",
  "1 Collector Ouphe",
  "2 Council's Judgment",
  "2 Ethersworn Canonist",
  "1 Faerie Macabre",
  "1 Celestial Purge",
  "1 Veil of Summer",
  "1 Qasali Pridemage",
  "2 Surgical Extraction"
]