[
"1 Badlands",
"1 Fiery Islet",
"4 Polluted Delta",
"4 Scalding Tarn",
"3 Tropical Island",
"1 Underground Sea",
"2 Volcanic Island",
"4 Wasteland",
"1 Spell Pierce",
"4 Lightning Bolt",
"4 Force of Will",
"4 Daze",
"4 Brainstorm",
"2 Abrupt Decay",
"2 Preordain",
"4 Ponder",
"2 True - Name Nemesis",
"4 Tarmogoyf",
"3 Wrenn and Six",
"4 Delver of Secrets",
"2 Gurmag Angler",
"Sideboard",
"1 Blue Elemental Blast",
"2 Liliana's Triumph",
"2 Plague Engineer",
"1 Pyroblast",
"1 Red Elemental Blast",
"1 Submerge",
"2 Surgical Extraction",
"3 Thoughtseize",
"2 Winter Orb"
]